### ISSUE TITLE
The string "Search IsThereAnyDeal for '...'" is too long

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1303]
### Current Behavior (if any)
When activating the item "Context Menu" / "Search IsThereAnyDeal for '...'" in the add-on settings, highlighting text on web pages and displaying the context menu, the context menu itself becomes very large due to the line "Search IsThereAnyDeal for", obscuring the content ...
![2021-11-06_14-05-32](https://user-images.githubusercontent.com/3509797/140607609-7eb37260-68ca-4ef6-bd4d-24f0aac1e1ea.png)

### Desired Behavior
I suggest shortening the context menu item to "Search IsThereAnyDeal" or even "Search ITAD".
Another option is to make a submenu for all ITAD searches.

### Motivation / Use Case for Changing the Behavior
People use the browser for more than just finding prices for games. And when they often find an unnecessary tool intrusive, they try to get rid of it. In this case, at least disable the display of this item in the context menu. In addition, it gets in the way at low screen resolutions.

**Comment by candela97** [comment]
This is more of a browser issue I think. Is that Firefox you're using? This is what I get on Chrome with the default "Search Google for..."":
![螢幕擷取畫面 2021-11-06 200053](https://user-images.githubusercontent.com/54083835/140608837-c89e73df-de51-4eaf-95ab-1df9f9a7ce35.jpg)

> People use the browser for more than just finding prices for games. And when they often find an unnecessary tool intrusive, they try to get rid of it. In this case, at least disable the display of this item in the context menu.

This reasoning doesn't make much sense though, since you opted into this feature yourself, but yeah there may be ways to improve this. Having a submenu seems like a good idea.

**Comment by MxtOUT** [comment]
A submenu is automatically being created when an extension adds more than one context menu entry.
I also think that displaying the search string is unnecessary, but I'd like to keep IsThereAnyDeal instead of ITAD
