### ISSUE TITLE
[BUG] Unable to add AugmentedSteam Icon to Firefox Toolbar

### ISSUE THREAD

**Issue by J-SoG-YK** [IsThereAnyDeal/AugmentedSteam#1445]
### Expected Behavior
AugmentedSteam icon appearing on Firefox toolbar after install or ability to add icon from palette via Customize Toolbar context menu.

### Actual Behavior
Icon neither appears on toolbar nor available from Customize Toolbar palette.

### Steps to Reproduce the Problem

  1. Install extension from Mozilla Add-on web page.
  2. 
  3.

### Specifications

  - Augmented Steam Version: 2.3.2
  - Browser Version: 102.0 (64-bit)

![Firefox Toolbar](https://user-images.githubusercontent.com/52582727/177219516-a8a319c4-6e33-4597-8d0f-fafad1b0ee28.png)
![Firefox Cutomize Toolbar Palette](https://user-images.githubusercontent.com/52582727/177220375-4b70e94f-7eba-4589-89a6-931487cfaecb.png)

**Comment by candela97** [comment]
I think this is a browser quirk rather than a bug. Seems like FF only shows the icon if the extension has a browser action, i.e. a custom menu or UI when you click on it. We could add a action that does nothing to "fix" this, but that doesn't make much sense.

I'll open another issue and pitch some ideas for what we can do with a menu.

**Comment by MxtOUT** [comment]
Like @candela97 said, this is not a bug and should better be formulated as a feature request.
