### ISSUE TITLE
[FEATURE REQUEST] Show average completion time

### ISSUE THREAD

**Issue by avi12** [IsThereAnyDeal/AugmentedSteam#1533]
### Desired Behavior
Add a section to the game listing of average completion time as reported by users
![image](https://user-images.githubusercontent.com/6422804/203873076-17937784-3791-4288-b31d-1b7f22d59f2c.png)

### Motivation / Use Case for Changing the Behavior
To evaluate how much time I can allocate to a game I'm considering buying

**Comment by candela97** [comment]
You mean showing the time for "All Styles"?

**Comment by avi12** [comment]
All the time ranges, yes, similar to the screenshot

**Comment by candela97** [comment]
In case you didn't know, we already have an option to show HLTB data on store pages, it's just missing the time for All Styles.

**Comment by avi12** [comment]
Interesting, I'll check it out

**Comment by avi12** [comment]
It's enabled by default; I just never noticed it until you mentioned it
![image](https://user-images.githubusercontent.com/6422804/204165209-b97920d9-6f52-4b1a-b51d-f2af995c52b1.png)

I think having it as a Player Data-style table will be more noticeable compared to the small rectangle on the right panel

**Comment by candela97** [comment]
Actually I was thinking about moving all 3rd party data to the right-hand column, since game descriptions can get pretty long, see #214. But of course that's still up for debate.

In any case, I think this issue is resolved for now? It's not clear what the "All Styles" metric stands for at a glance, and this feature has remained the same since ES. If anyone wants to see it, they can click more details.
