### ISSUE TITLE
[FEATURE REQUEST] Replace the Steam player by the YouTube player

### ISSUE THREAD

**Issue by avi12** [IsThereAnyDeal/AugmentedSteam#1625]
### Current Behavior
When visiting a game listing page and viewing the videos in the carousel, they're played through the Steam player

### Desired Behavior
Replace (or at least add the option to replace) the player with YouTube's

### Motivation / Use Case for Changing the Behavior
IMO it's way more convenient and user friendly

I'm pretty sure it should be possible to take the YouTube player as a frame and play any desired video in it, similar to how Google Drive does it

**Comment by candela97** [comment]
We won't be able to find the corresponding video on YouTube without using its search API though. https://github.com/IsThereAnyDeal/AugmentedSteam/issues/936#issuecomment-758576758 still stands.

**Comment by avi12** [comment]
Is there a chance that you do a little research on Google Drive to see how the Drive team is using the YouTube player to play a user's video?

**Comment by candela97** [comment]
Google owns YouTube, so I'm sure their own services get special treatment 😏. We, on the the other hand, need to operate by API quotas, and IIRC the limit is 100 searches per app per day, which we'll reach in no time given the amount of downloads we have. That's why a server-side solution is required.

**Comment by avi12** [comment]
Why do you need the YouTube Search API?

**Comment by candela97** [comment]
Otherwise we won't be able to establish the link between a video on Steam and a video on YouTube. Unless somebody compiles a list of Steam videos with their corresponding YouTube video ids. If you mean modifyng the player to YouTube's style, that's not possible either since the entire "player" is fetched from Google servers.

We can of course create our own "enhanced" version of the Steam player, but that would be a lot of work 😅.

**Comment by candela97** [comment]
No, unless you upload that video to YouTube. Google isn't gonna share their intellectual property and server bandwidth for free 🤣.

**Comment by avi12** [comment]
True, which is why reverse engineering is a thing; sadly I'm not an expert in this field

**Comment by avi12** [comment]
After a quick Google Photos investigation, even opening the `<iframe>`'s `src` in a new tab makes the video unplayable
I wonder if there is a way around it
