### ISSUE TITLE
[BUG] Infinity current value in wishlist

### ISSUE THREAD

**Issue by evil-pechenka** [IsThereAnyDeal/AugmentedSteam#1652]
### Expected Behavior

Wishlist displays the total amount

### Actual Behavior

Wishlist does not show the total amount

### Steps to Reproduce the Problem

  1. I open the wishlist
  2. Watching stats

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Chrome 114.0.5735.134

![2023-06-18_16-31-04-%t](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/109512933/bd5ae018-7c23-4f30-92c4-390cdec548a2)

Perhaps this is due to some games in the wishlist, I have no idea.

I'm attaching a wishlist just in case.
[Wishlist.zip](https://github.com/IsThereAnyDeal/AugmentedSteam/files/11781663/Wishlist.zip)

**Comment by gmikhail** [comment]
I have a similar problem. But in my case it just shows a large number:

![2023-06-20 113607](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/4838367/580112ce-28e6-4dfb-b0fa-efff0488aece)

An interesting note - it looks like the total price consists of prices as a string (at least in the beginning):

Total price: 895001799002199031808,00₴
1st game: 895,00₴
2nd game: 1 799,00₴
3rd game: 2 199,00₴
4th game: 1 699,00₴
5 and 6 has no price.

Maybe instead of numbers, strings are concatenated?
