### ISSUE TITLE
[BUG] Unable to add S&Box to wishlist.

### ISSUE THREAD

**Issue by rokejulianlockhart** [IsThereAnyDeal/AugmentedSteam#1731]
### Expected Behavior

The application should have been added to my Steam wishlist.

### Actual Behavior

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/42837531/6da14a8b-eb81-410e-945a-aff4d82d7ebf)

### Steps to Reproduce the Problem

  1. https://steamcommunity.com/app/590830
  2. https://steamcommunity.com/app/590830#:~:text=add%20to%20your%20wishlist%20

### Specifications

  - Augmented Steam Version: https://addons.mozilla.org/firefox/downloads/file/4054613/augmented_steam-2.5.0.xpi
  - Browser Version: https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-116.0.3-1.1.x86_64.rpm

**Comment by candela97** [comment]
That game doesn't have a visible store page yet, so it can't be wishlisted. It's difficult to determine whether a game can be wishlisted from the community, so we always show the button regardless.

**Comment by rokejulianlockhart** [comment]
@candela97, then shouldn't the error message at least be improved to state that?

**Comment by candela97** [comment]
It's not easy to determine whether the error is due to Steam server hiccups, not being logged in to the Store,  wishlisting the same game twice (or removing a nonexistent game), or, as in the case here, trying to wishlist a game that can't be wishlisted, so we just issue a generic error. The method this feature uses is exactly the same as the native one on store pages, so since the store page is a click away, you can turn to the native method if this fails.
