### ISSUE TITLE
[FEATURE REQUEST] Add option to disable blurring of adult content on Steam Profiles

### ISSUE THREAD

**Issue by RafGamer** [IsThereAnyDeal/AugmentedSteam#1803]
### Current Behavior (if any)
In some countries (Germany for example) games with adult content are blurred on steam profile showcases. Regardless of the account settings. The same applies for artworks belonging to these games because the community hubs are also blocked.
This is because these games arent available in steam store because of laws that require age verifications that arent present on steam.

### Desired Behavior
An option to disable the blurring of content belonging to these games. Ive checked and it seems it would be enough to remove the `app_has_adult_content` class from the `<div>` for the game showcases and the `has_adult_content` from `<a>` for the artworks.

### Motivation / Use Case for Changing the Behavior
To be able to see steam profiles like they are intended to be seen.

**Comment by candela97** [comment]
You can use a content blocker like uBlock Origin to remove unwanted class names. Content blockers are the superior tool for such purposes because you can easily edit custom rules when something breaks, whilst if we add such features to the extension, it can only be updated when we release a new version (and sadly we don't have a great track record at keeping up with Steam changes 😅).

If you're unsure how to write a filter for this, link me a sample profile page and I'll help out.

**Comment by RafGamer** [comment]
@candela97 
Thanks for offering your help. I've managed to write a filter myself. For anyone wondering, this works:
`steamcommunity.com##div:remove-class(app_has_adult_content)`
`steamcommunity.com##a:remove-class(has_adult_content)`

It didn't even come to my mind that the easiest way to do that was with uBlock Origin. I even wrote a userscript that removes the class names. 😅
