### ISSUE TITLE
[FEATURE REQUEST]: Colored band for adult games

### ISSUE THREAD

**Issue by SabreRunner** [IsThereAnyDeal/AugmentedSteam#1810]
### Current Behavior (if any)
Steam presents a notice under the image carousel if this is an adult game. But it doesn't always show for all adult games.

### Desired Behavior
Augmented Steam will recognise that a game is tagged as adult (and/or some other kinds of adult-related tags) and display a colored band over the title image like there is one for DLC, Mods, Soundtracks, etc...

### Motivation / Use Case for Changing the Behavior
Notice adult games more quickly and avoid unwanted imagery.

**Comment by candela97** [comment]
The most reliable way to avoid seeing adult games is to head to account settings and uncheck the corresponding options under mature content preferences, then the capsule images should be blurred out.

We can't do any better than Steam does since we only have info from the page itself, and tags are not reliable nor always present.
