### ISSUE TITLE
[BUG] Can't add games to cart at all on Firefox

### ISSUE THREAD

**Issue by GaussTek** [IsThereAnyDeal/AugmentedSteam#1851]
### Expected Behavior
Adding a game, and cart showing up so you can get the games.

### Actual Behavior
After clicking on the Add to Cart button, the game doesn't get added to a cart, and the popup confirming it doesn't show up.  This also happens when you try to add games from your wishlist. If I disable Augmented Steam, this works as intended.
It also works fine on my end using the main Steam application.

### Steps to Reproduce the Problem

  1. Click on the Add To Cart Button
  2. The little popup that confirms it doesn't show up
  3. Cart is empty

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Firefox 123.0.1 (Windows)

**Comment by subZEROx265** [comment]
Yeah, same here on Chrome and Firefox. I guess Steam latest update on shopping cart and private game broke Augmented Steam.

**Comment by zxc23** [comment]
Same issue.

Chrome Version 122.0.6261.95 (Official Build) (64-bit)
Augmented Steam Version: 3.0.0

**Comment by ScottCWebster** [comment]
I had the same issue on Chrome. If I go into the Augmented Steam's settings and un-check the "Prevent redirection when adding items to your Cart" option, I'm able to add things to my cart again.

Since Steam's latest store update includes its own prompt to continue browsing without going to the cart after adding an item, this option may now be redundant.

Chrome Version 122.0.6261.112 (Official Build) (64-bit)
Augmented Steam Version: 3.0.0

**Comment by candela97** [comment]
Yes, please see the above comment and disable that option. It's now deprecated and will be removed in future versions.

**Comment by cutterjohn** [comment]
same, just sent an email after removing pihole as DNS, no go

disable pihole altogether no go

dosable ublock origin no go

try chromium and chrome no augmented steam, hey it works!

disable augmented steam on firefox (123.01) hey now it works again!

BTW this was all under OpenSUSE TW 20240310-0, all browsers are latest available as are all browser plugins...
