### ISSUE TITLE
[BUG] Several bugs in Augmented Steam

### ISSUE THREAD

**Issue by 10522** [IsThereAnyDeal/AugmentedSteam#1889]
1. This button is not working:

![1111111](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/59209149/0f5523ed-9dfb-49e2-bb6e-57c5e41d391c)

2. This tooltip is not displayed:

![3333333](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/59209149/3ab35737-3a88-40d3-b934-9c20222816c1)

3. This information is displayed even if "Show player count information" is disabled:

![2222222](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/59209149/46c55adb-9f19-4ea3-9dee-8b847b7d4900)

### Specifications

  - Augmented Steam Version: 3.1.0
  - Browser Version: Google Chrome 123.0.6312.86

**Comment by candela97** [comment]
1. Works fine on my end.
2. We don't touch this. Please test on a brand new profile with only AS enabled.
3. Will be fixed by #1877.

**Comment by candela97** [comment]
Can you share which app pages are you seeing these issues?

**Comment by candela97** [comment]
Links on error pages work for me:
![螢幕擷取畫面 2024-07-13 000138](https://github.com/user-attachments/assets/db215e87-e4a5-497b-84d9-44e5ae24d191)

The others I have opeded PRs to fix them, thanks for reporting! Since the original issue doesn't seem to be a bug, I'm going to close this for now. Please log new issues for new bugs so they're easier to track.

**Comment by candela97** [comment]
Ah, I see the issue now
