### ISSUE TITLE
[BUG] Achievement Sorting By Date Unlocked Does Nothing

### ISSUE THREAD

**Issue by mslowikowski** [IsThereAnyDeal/AugmentedSteam#1908]
### Expected Behavior

Achievements are ordered the date that they were unlocked according to the Ascending/Descending toggle when the Sort By drop down is set to `Date Unlocked`

### Actual Behavior

Achievements are ordered by the default order set by Steam

### Steps to Reproduce the Problem

  1. Log-in to steam
  2. Navigate to an achievement page (https://steamcommunity.com/id/<player identifier>/stats/<game id>/achievements/)
  3. Change Sort By drop down to `Date Unlocked`

### Specifications

  - Augmented Steam Version: 3.1.1
  - Browser Version: Firefox 124.0.2 (64-bit)

**Comment by candela97** [comment]
Are there any errors in the browser console (F12)?

**Comment by mslowikowski** [comment]
> Are there any errors in the browser console (F12)?

No there are no errors in the console.

**Comment by Sakr3d** [comment]
This occurs for me in Chrome as well. Chrome version: 124.0.6367.61 (Official Build) (64-bit), Augmented Steam version: 3.1.1

Console log shows the following:
profile_stats.js:66  Augmented Steam v3.1.1  https://augmentedsteam.com
profile_stats.js:7 Feature loading complete, 7 successfully loaded, 0 failed to load, 0 didn't load due to dependency errors
achievements/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

[steamcommunity.com-1713792226240.log](https://github.com/IsThereAnyDeal/AugmentedSteam/files/15063625/steamcommunity.com-1713792226240.log)

**Comment by candela97** [comment]
Can I ask what language your browser is set to?

**Comment by Sakr3d** [comment]
Here's the log.

[steamcommunity.com-1713821286248.log](https://github.com/IsThereAnyDeal/AugmentedSteam/files/15068753/steamcommunity.com-1713821286248.log)

My console is not showing FAchievementSort.ts like your image is. I'm showing profile_stats.js

**Comment by candela97** [comment]
Thanks, I got it. Date formats are region-dependent, so there're 2 types for English, month/day and day/month.

**Comment by candela97** [comment]
Please give this branch a test under your normal setup and see if it works https://github.com/IsThereAnyDeal/AugmentedSteam/actions/runs/8802153019

**Comment by Sakr3d** [comment]
Sorry for the delay. I tested the branch and sorting worked as expected.

![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/37714077/3fd9efff-44db-4ead-9a36-e5b98aaa42eb)
