### ISSUE TITLE
[FEATURE REQUEST] Replace Steam-selected "Your Tags" list with user-selected tags

### ISSUE THREAD

**Issue by felixlang** [IsThereAnyDeal/AugmentedSteam#986]
### Current Behavior (if any)

There are two areas of Steam that contain a section titled "Your Tags." One is near the bottom of the left sidebar on the main page ([here](https://steamuserimages-a.akamaihd.net/ugc/1651097228977330284/E78341D4D8EC0B818916D00B67E73CE6CD22DF22/)), and the other is a tab on Steam's dedicated [tag page](https://store.steampowered.com/tag/browse/). The tags in the section on the main page are selected by Steam based on games you have recently played. The tags in the section on the dedicated tag page are based on tags you have applied to individual games on Steam, sorted by frequency of application.

### Desired Behavior

Ideally both "Your Tags" sections could be directly populated and maintained by us, instead of by Steam. Primarily though, it is the section on the sidebar of the main page where this functionality would be most useful and appreciated, both because it is more easily accessible, and because the current way in which Steam selects those tags (recent playtime) is completely inane and useless.

### Motivation / Use Case for Changing the Behavior

There are many different types of games I enjoy, but for two examples I'll use Metroidvanias and Souls-likes. Just as with all other global tags, these two types of games have dedicated pages on the Steam store ([here](https://store.steampowered.com/tags/en/Metroidvania) and [here](https://store.steampowered.com/tags/en/Souls-like/)). I like to frequently check these pages for new releases, as well as the pages for other categories of games I am interested in, especially during sales. However, Steam has no way to quickly navigate to them. Beyond saving each tag's dedicated page as a bookmark in my browser (which I am currently doing), there is no way to save our own preferred list of tags on Steam.

I was hopeful that the new Steam Labs browsing update would fix this problem, but even though there are more categories that are easily accessible now, Metroidvanias and Souls-likes (and many other types of games I like) are not among them, not even as a secondary option on the main categories' Steam pages (e.g. there is no Souls-like tag under the "Narrow by tag" sidebar.

**Comment by candela97** [comment]
Sounds good, and shouldn't be too hard to implement either since we can reuse Steam's methods, though by default only the first 5 tags are rendered. For the home page, we can also refresh the tags listed under the "Your Store" dropdown:

1. Set `GDynamicStore.s_rgRecommendedTags` to what the user prefers (A list of tag names and their corresponding tagids can be retrieved from: `https://store.steampowered.com/tagdata/populartags/english`)

2. Run
```js
// store navigation bar, refreshes the tags list under "Your Store"
GDynamicStore.PopulateRecommendedTagList();
````
refs: https://github.com/SteamDatabase/SteamTracking/blob/5f4c5c5a771d8c4f59f0d402c56adcdf60518597/store.steampowered.com/public/javascript/dynamicstore.js#L1143

```js
// left sidebar, appends new tags and skips those already in "Browse by genre"
GHomepage.RenderRecommendedTags();
````
refs: https://github.com/SteamDatabase/SteamTracking/blob/5f4c5c5a771d8c4f59f0d402c56adcdf60518597/store.steampowered.com/public/javascript/home.js#L2048

What's left to decide is where to put the setting?
a) new section under `https://store.steampowered.com/account/preferences`?
b) "customize your tags" button somewhere on the home page with a popup?

Steam's autocomplete widget could also come in handy: https://github.com/SteamDatabase/SteamTracking/blob/5f4c5c5a771d8c4f59f0d402c56adcdf60518597/store.steampowered.com/public/javascript/app_tagging.js#L1091

**Comment by felixlang** [comment]
As far as where to put the setting: I don't know how convenient this would be to program, but I think an easy way it would work for users would be to insert a text entry box below the Your Tags heading on the main page, and then we could just type in the tags we want to appear there. This would be similar to how it looks on Steam's [search page](https://store.steampowered.com/search/), on the right sidebar under the "Narrow by Tag" heading.

Sorry, I don't know anything about writing code so I won't be much help here.

**Comment by candela97** [comment]
For the record, I haven't forgotten about this, and still think this is a useful feature to have. Back then I was waiting for the outcome of this experiment: https://store.steampowered.com/news/group/35143931/view/2379537344925141077 since we'd be modifying that menu. But things have settled down now, so hopefully I'll get to this soon.

**Comment by candela97** [comment]
You can now search for tags and categories in the search box as well, a long-waited change. See https://store.steampowered.com/news/app/593110/view/3686801719533364952.

That more or less covers this feature, I guess.

**Comment by MxtOUT** [comment]
I agree with @candela97.
While it may not be as easily accessible as directly clicking on a user defined tag page in the sidebar, in combination with our quick focus feature (press "s" to focus the search box) it becomes fairly quick to navigate to any tag page.
If this is still not enough for you then this is what browser bookmarks are there for imo.
